name: ChestShop
main: org.simpleshop.SimpleShop
version: 1.0.0
api-version: '1.20'
author: Failxos
softdepend: [Vault]
description: >
  Simple shop plugin controlled by signs. Sign format:
  Line 1: [shop]
  Line 2: price
  Line 3: B (owner buys) or S (owner sells)
  Line 4: filled in automatically by the plugin based on the item in the chest
